matrix:
  include:
  - dist: bionic
    language: java
    jdk: openjdk11
    before_install:
    - export JCC_JDK=/usr/lib/jvm/java-11-openjdk-amd64
    - sudo ln -s /usr/lib/jvm/java-11-openjdk-amd64/lib/server/libjvm.so /usr/lib/libjvm.so
    - sudo ln -s /usr/lib/jvm/java-11-openjdk-amd64/lib/libjava.so /usr/lib/libjava.so
    - sudo apt-get update
    - sudo apt-get install python3.6
    - sudo apt-get install python3-pip
    - python3 -m pip install --upgrade --user setuptools
    - python3 -m pip install --upgrade --user wheel
    - python3 -m pip install --upgrade --user JCC
    script: "travis/make_dist.sh"
    # before_deploy:
    # - python3 -m pip install --user twine
    # - python3 -m pip install --user urllib3[secure]
    # deploy:
    #   provider: pypi
    #   #server: https://test.pypi.org/legacy/
    #   user: "nighres"
    #   # using plain text password for testpypi, when switching to real pypi use encrypted (below)
    #   password:
    #       secure: "S010GtC13p8KB6lXiuPVDhCWk++PGCPGVmX9Kd7AL91c6KTSRnPAoWCGNPrgbPtKjapiuYd2f4D2iWuURdpI6OYUahzH/dlHJVDHJNZ3XFfE7eIylwnKxKGtlXxu0Tm+JLrN1gprU3bCWH9MbpWINgmccCXO+YJfDcsVzFd/ywJ2oo4n7fntAMOhj3djRlkXh57pPLM3LKQeHSjjx8RMYTwKCVUAMB76iUnfcow7Lcmo73KghD/71uJEr8AA0RDB0uC8x9DAR/RL4g8JL1PR0ocOJ9iHsBus1jHxsxw+ISVP6iCiJNqKUKV3JbZ7PJ997YxpmInTBJNnAzGkne7dy77f10m3RMHKjsFimg0yQouPGDi8hBk2/0i2piDErq6lf2x4rTvWsIBhKroaNUjvltFl2N6OCGMzN1xsnYtzrUWc5DuY9XerEVFkPIpd+i/ojyBqU+ssj5fwMRNoACWxFZ/Hxf1YwEpU9OgBXfiU3SK4VwGPf2s2zXbqTT+ogiNB+EYhdrAaPaFgjLkfoLjLxpSnmE2WTJphmLFCx9ZRbW5tS++K+iJ5Cyc+pTjIfzb7KLLPAvhD99VEikutp8X91pRT1LTUWV921ymD0BKtF4K2eUJZSYiVO4ct9sl2GQIi0v1rRfDWxN+9pUnCOP1cPHnXTe0qGH26ulf48lQejm8="
    #   skip_cleanup: true
    #   on:
    #     tags: true
    #     branch: master
        # condition: $TRAVIS_PYTHON_VERSION = "2.7" once we run travis against
        # multiple python versions, this ensures that the package will be deployed only once

notifications:
  email: false
